# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65e0539a557697994f64eaeec6296e5a7975b5abd4bf604efc4a116d1cad0ab712ad46ff38e7dcde45fa8202d908c53010118142403d8433dea32dd7a520182e

test:
  secret_key_base: d0fe4df7d3a3b0cf191709d37e1f4465f921e6ae3816af1061554868231bdfa68210ccc926672f980a2c15acc0371893561a8dc7179875e1450c54fe862e406e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: sdfasdfasdfasdfsadfasdf
